# Combine given security group with the one generated by webapp module for the
# worker module to use.
# var "SecurityGroupsAll" {
#   description = "Given security groups plus webapp security group"
#   default     = ["${module.webapp.SecurityGroup}", "${var.SecurityGroups}"]
# }

# Generate the worker application.
