# module worker {
#   source = "../../modules/worker"
#
#   StackName                  = "${var.StackName}"
#   ApplicationName            = "${aws_elastic_beanstalk_application.hybox.name}"
#   VersionLabel               = "${aws_elastic_beanstalk_application_version.hybox.name}"
#   KeyName                    = "${join(",", ${var.KeyName})}"
#   MinSize                    = "${var.WorkerMinSize}"
#   MaxSize                    = "${var.WorkerMaxSize}"
#   PrivateSubnets             = "${join(",", ${var.PrivateSubnets})}"
#   SecurityGroups             = "${join(",", ${var.SecurityGroupsAll})}"
#   HostedZoneName             = "${var.HostedZoneName}"
#   SecretKeyBase              = "${var.SecretKeyBase}"
#   FcrepoUrl                  = "${var.FcrepoUrl}"
#   SolrUrl                    = "${var.SolrUrl}"
#   ZookeeperHosts             = "${var.ZookeeperHosts}"
#   RedisHost                  = "${var.RedisHost}"
#   RedisPort                  = "${var.RedisPort}"
#   RDSDatabaseName            = "${var.RDSDatabaseName}"
#   RDSUsername                = "${var.RDSUsername}"
#   RDSPassword                = "${var.RDSPassword}"
#   RDSHostname                = "${var.RDSHostname}"
#   RDSPort                    = "${var.RDSPort}"
#   QueuePrefix                = "${var.QueuePrefix}"
#   DefaultQueue               = "${aws_sqs_queue.default.arn}"
#   DefaultQueueName           = "${aws_sqs_queue.default.name}"
#   BeanstalkSNSTopic          = "${var.BeanstalkSNSTopic}"
#   InstanceType               = "${var.WorkerInstanceType}"
#   HealthReportingSystemType  = "${var.WorkerHealthReportingSystemType}"
#   IamInstanceProfile         = "${aws_iam_instance_profile.application.arn}"
#   UploadBucket               = "${aws_s3_bucket.upload.arn}"
#   SSLCertificateId           = "${var.SSLCertificateId}"
#   HoneybadgerApiKey          = "${var.HoneybadgerApiKey}"
#   LogzioKey                  = "${var.LogzioKey}"
# }
